BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY,
    email VARCHAR,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS articles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR NOT NULL UNIQUE,
    source VARCHAR NOT NULL,
    title TEXT NOT NULL,
    authors VARCHAR[],
    journal VARCHAR,
    abstract TEXT,
    url TEXT NOT NULL,
    published_at TIMESTAMP WITHOUT TIME ZONE,
    fetched_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscriptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR NOT NULL,
    keywords VARCHAR[] NOT NULL,
    authors VARCHAR[] NOT NULL DEFAULT '{}'::VARCHAR[],
    journals VARCHAR[] NOT NULL DEFAULT '{}'::VARCHAR[],
    check_interval_hrs INTEGER NOT NULL DEFAULT 24,
    language VARCHAR NOT NULL DEFAULT 'any',
    last_checked_at TIMESTAMP WITHOUT TIME ZONE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_subscriptions_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS annotations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id INTEGER NOT NULL UNIQUE,
    text_ru TEXT NOT NULL,
    model_used VARCHAR NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_annotations_article
        FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS subscription_articles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id INTEGER NOT NULL,
    article_id INTEGER NOT NULL,
    notified_telegram BOOLEAN NOT NULL DEFAULT FALSE,
    notified_email BOOLEAN NOT NULL DEFAULT FALSE,
    found_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_subscription_articles_subscription_article
        UNIQUE (subscription_id, article_id),
    CONSTRAINT fk_subscription_articles_subscription
        FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE CASCADE,
    CONSTRAINT fk_subscription_articles_article
        FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id
    ON subscriptions (user_id);

CREATE INDEX IF NOT EXISTS idx_subscription_articles_subscription_id
    ON subscription_articles (subscription_id);

CREATE INDEX IF NOT EXISTS idx_subscription_articles_article_id
    ON subscription_articles (article_id);

COMMIT;
